package helloworld
import com.example.aibi.entity.Person
import com.example.aibi.entity.Company
import java.util.Map
import java.util.Set

// 将num映射到a和b之间
function Double fx(Integer num,Integer a,Integer b){
    if(num>b){
        return 1d;
    }
    if(num<a){
        return 0.5d;
    }
    return (double)(num-a)/(double)(b-a);
}

// 计算分数
rule "Person_point"
    no-loop true
    salience 98
    when
        $person:Person()
    then
        int aca = $person.getCountAca();
        int direc = $person.getCountDirec();
        int officer = $person.getCountOfficer();
        int tenure = $person.getCountTenure();
        int rank = $person.getRank();
        double point = (fx(aca,1,3)+fx(direc,1,3)+fx(officer,1,4)+fx(tenure,1,4)+fx(rank,1,100))/4;
        $person.setPoint(point);
        update($person)
        System.out.println("匹配到规则person");
end

// 计算公司分数
rule "Company_point"
    no-loop true
    salience 98
    when
        $company:Company()
    then
        int scale = $company.getPersonScale();
        double point = fx(scale,1,250);
        $company.setPoint(point);
        update($company)
        System.out.println("匹配到规则company");
end

